name: archive
on:
  workflow_dispatch:
  schedule:
    # Every 6 hours
    - cron: "0 */6 * * *"

jobs:
  update_archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Run archive script
        run: |
          chmod +x ./tools/archive.sh
          ./tools/archive.sh
        shell: bash

      - name: Update Git URL
        run: git remote set-url origin git@github.com:grilme99/RobloxVersionArchive.git
        shell: bash

      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Update archive'
          default_author: github_actions
